/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommissionEntry {
  'merchantName' : string,
  'transactionDate' : Time,
  'commissionEarned' : number,
  'transactionAmount' : number,
  'category' : string,
  'commissionRate' : number,
  'transactionId' : string,
}
export interface FrontPhoto {
  'front_id_card_image' : Uint8Array,
  'front_id_card_image_name' : string,
}
export interface Stats {
  'averageCommissionRate' : number,
  'totalTransactionVolume' : number,
  'totalCommissionEarned' : number,
  'totalTransactions' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addCommission' : ActorMethod<
    [string, number, number, Time, string, string],
    undefined
  >,
  'addPhoto' : ActorMethod<[bigint, FrontPhoto], undefined>,
  'deleteCommission' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'getAllCommissions' : ActorMethod<[], Array<CommissionEntry>>,
  'getAllPhotos' : ActorMethod<[], Array<FrontPhoto>>,
  'getPhoto' : ActorMethod<[bigint], [] | [FrontPhoto]>,
  'getStats' : ActorMethod<[], Stats>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];