/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FrontPhoto = IDL.Record({
  'front_id_card_image' : IDL.Vec(IDL.Nat8),
  'front_id_card_image_name' : IDL.Text,
});
export const CommissionEntry = IDL.Record({
  'merchantName' : IDL.Text,
  'transactionDate' : Time,
  'commissionEarned' : IDL.Float64,
  'transactionAmount' : IDL.Float64,
  'category' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'transactionId' : IDL.Text,
});
export const Stats = IDL.Record({
  'averageCommissionRate' : IDL.Float64,
  'totalTransactionVolume' : IDL.Float64,
  'totalCommissionEarned' : IDL.Float64,
  'totalTransactions' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCommission' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Nat, FrontPhoto], [], []),
  'deleteCommission' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'getAllCommissions' : IDL.Func([], [IDL.Vec(CommissionEntry)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(FrontPhoto)], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(FrontPhoto)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FrontPhoto = IDL.Record({
    'front_id_card_image' : IDL.Vec(IDL.Nat8),
    'front_id_card_image_name' : IDL.Text,
  });
  const CommissionEntry = IDL.Record({
    'merchantName' : IDL.Text,
    'transactionDate' : Time,
    'commissionEarned' : IDL.Float64,
    'transactionAmount' : IDL.Float64,
    'category' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'transactionId' : IDL.Text,
  });
  const Stats = IDL.Record({
    'averageCommissionRate' : IDL.Float64,
    'totalTransactionVolume' : IDL.Float64,
    'totalCommissionEarned' : IDL.Float64,
    'totalTransactions' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCommission' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Nat, FrontPhoto], [], []),
    'deleteCommission' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'getAllCommissions' : IDL.Func([], [IDL.Vec(CommissionEntry)], ['query']),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(FrontPhoto)], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(FrontPhoto)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };